version: '3'

services:
  backend:
    build: './encuesta'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./encuesta:/code
    ports:
      - '8000:8000'
  frontend:
    build: './frontend'
    command: 'npm dev'
    volumes:
      - './frontend:/usr/src/app'
    ports:
      - '3000:3000'
    