# Generated by Django 3.0.7 on 2022-01-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content2',
            field=models.TextField(default=''),
        ),
    ]
