# Generated by Django 3.2.4 on 2021-07-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
