# Generated by Django 3.2 on 2021-08-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='fotos/'),
        ),
    ]
