# Generated by Django 3.2.6 on 2021-08-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0002_alter_imagen_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeimage',
            name='id_image',
        ),
        migrations.AddField(
            model_name='imagen',
            name='like_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imagenes.likeimage'),
        ),
    ]
