# Generated by Django 3.2 on 2021-08-02 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imagenes', '0003_auto_20210801_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_api.userprofile'),
        ),
    ]
