# Generated by Django 3.2.6 on 2021-08-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagenes', '0004_alter_likeimage_cant_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeimage',
            name='op',
            field=models.BooleanField(default=False),
        ),
    ]
